``pytest.raises`` now works with exception classes that look like iterables.
